channels:
- pytorch
- anaconda
- defaults
- huggingface
- conda-forge
dependencies:
- python==3.8.5
- pip==21.2.4
- pytorch==1.7.1
- torchvision==0.8.2
- torchaudio==0.7.2
- cudatoolkit==11.0.221
- nvidia-apex==0.1
- gxx_linux-64==7.2.0
- datasets==1.18.4
- scikit-learn==0.23.2
- pip:
  - azureml-defaults==1.39.0
  - azureml-mlflow==1.39.0
  - azureml-telemetry==1.39.0
  - azureml-train-core==1.39.0
  - mlflow==1.24.0
  - transformers==4.17.0
  - inference-schema[numpy-support]==1.3.0
  - applicationinsights==0.11.10
  - fsspec[archive]==2022.3.0
