name: GPT2_Finetuning_PTCA
display_name: GPT2 Finetuning PTCA
version: 18
type: command
description: GPT2 Model Finetuning Task with PTCA Image
tags: {category: LLM, contact: jambaykinley@microsoft.com, type: GPT2}
inputs:
  weights_path: 
    type: uri_folder
    description: The model checkpoint for weights initialization.
  tokenizer_path:
    type: uri_folder
    description: Pretrained tokenizer name or path if not from model_name.
  config_path: 
    type: uri_folder
    description: Pretrained GPT2 model configuration.
  train_path: 
    type: uri_folder
    description: Directory containing pre-processed training data.
  validation_path: 
    type: uri_folder
    description: Directory containing pre-processed validation data.
    default: Empty
  block_size: 
    type: integer
    description: Block size for text in each training example.
    default: 512
  batch_size: 
    type: integer
    description: Batch size per step on each device.
    default: 26
  num_train_epochs: 
    type: integer
    description: Number of training epochs.
    default: 20
  fp16: 
    type: boolean
    description: Use mixed precision.
    default: true
  ort: 
    type: boolean
    description: Use ORTModule.
    default: true
  deepspeed: 
    type: boolean
    description: Use deepspeed.
    default: true
outputs:
  weights_output:
    type: uri_folder
  tokenizer_output:
    type: uri_folder
  config_output:
    type: uri_folder
code: .
environment: azureml:ptca-hf-transformer-train:4
distribution:
  type: pytorch
  process_count_per_instance: 4
command: >-
  python finetune.py 
  --model_path ${{inputs.weights_path}} 
  --tokenizer_path ${{inputs.tokenizer_path}}
  --config_path ${{inputs.config_path}}
  --train_path ${{inputs.train_path}} 
  --validation_path ${{inputs.validation_path}} 
  --block_size ${{inputs.block_size}}
  --batch_size ${{inputs.batch_size}}
  --num_train_epochs ${{inputs.num_train_epochs}}
  --ort ${{inputs.ort}}
  --fp16 ${{inputs.fp16}}
  --deepspeed ${{inputs.deepspeed}}
  --model_output ${{outputs.weights_output}}
  --tokenizer_output ${{outputs.tokenizer_output}} 
  --config_output ${{outputs.config_output}}
  --custom_hf
